### ISSUE TITLE
First Deliverable is Unclear

### ISSUE THREAD

**Issue by jenniferbusca** [learn-co-curriculum/react-static-components-lab#6]
The first deliverable is:
Two components have not been properly imported in src/App.js. Identify and debug the issue (hint: the stack trace when running npm test should point you in the right direction!)

I completed this lab and passed all tests without making any changes to the component imports. What is this deliverable asking?

**Comment by maxwellbenton** [comment]
Hi @jenniferbusca,

Thank you for spotting this and opening this issue. We've updated this lesson's instructions and starter code so that they correctly align. Students will now have to write the import statements as well as a component in JSX, rather than being giving the imports, which should resolve this issue for future students.

Thank you for contributing!
